[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
optimizer = true
optimizer_runs = 1_000_000
solc = "0.8.19" 
fs_permissions = [{ access = "read", path = "./snark-verifiers/data"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.optimizer_details]
constantOptimizer = false 
yul = false 